version: '3.8'

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./shared/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./services/auth_service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/attendance_db
      - JWT_SECRET=your-super-secret-jwt-key-at-least-32-characters-long
      - NODE_ENV=development
      - PORT=3001
      - FROM_EMAIL=noreply@germy.com
      - SMTP_HOST=smtp.ethereal.email
      - SMTP_PORT=587
      - SMTP_USER=elnora.greenholt@ethereal.email
      - SMTP_PASS=rcXCZYt1s5XPqhzEq8
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./services/auth_service:/app
      - /app/node_modules

  user-service:
    build: ./services/user_service
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/attendance_db
      - JWT_SECRET=your-super-secret-jwt-key-at-least-32-characters-long
      - NODE_ENV=development
      - PORT=3002
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./services/user_service:/app
      - /app/node_modules


volumes:
  postgres_data: